### ISSUE TITLE
.w export doesn't produce valid files

### ISSUE THREAD

**Issue by Yethiel** [NiklasHassdal/io_revolt#3]
No error while exporting it. RVGL freezes as it tries to load an imported and then exported stock track. Gotta be something in encode.py. Importing it with the plugin results in an error: 
```
Traceback (most recent call last):
  File "/home/yethiel/.config/blender/2.78/scripts/addons/io_revolt/__init__.py", line 69, in execute
    decode.import_world(self.properties.filepath, axis_conversion(to_up = self.up_axis, to_forward = self.forward_axis).to_4x4() * self.scale, self.include_objects, self.include_models, self.include_hitboxes, self.hide_hitboxes)
  File "/home/yethiel/.config/blender/2.78/scripts/addons/io_revolt/decode.py", line 104, in import_world
    decode_mesh(fh, bm, matrix)
  File "/home/yethiel/.config/blender/2.78/scripts/addons/io_revolt/decode.py", line 24, in decode_mesh
    vertices = [bm.verts.new(Vector(struct.unpack("=ffffff", fh.read(24))[:3]) * matrix) for x in range(vertex_count)]
  File "/home/yethiel/.config/blender/2.78/scripts/addons/io_revolt/decode.py", line 24, in <listcomp>
    vertices = [bm.verts.new(Vector(struct.unpack("=ffffff", fh.read(24))[:3]) * matrix) for x in range(vertex_count)]
struct.error: unpack requires a bytes object of length 24

location: <unknown location>:-1
```

**Comment by Yethiel** [comment]
After adjusting the bit sizes of the pack commands to the standard sizes, it gets stuck reading the polygons `... requires a bytes object of size 60`. That probably means that the file ends before it can read all polygons.
